//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCoMaster
    {
        public int CompId { get; set; }
        public string CompName { get; set; }
        public string HubName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
    }
}
