//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public string Customer_Name { get; set; }
        public string Delivery_Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Contact_No { get; set; }
        public string Customer_Email { get; set; }
        public string User_Email { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Pay_Method { get; set; }
        public string Order_Status { get; set; }
    }
}
