//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public int Id { get; set; }
        public string OderId { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime Date { get; set; }
    }
}
