//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int ProdId { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public byte[] ProdImage { get; set; }
        public string ProdImgContent { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
